### ISSUE TITLE
环境安装失败啊

### ISSUE THREAD

**Issue by jiadaoyun** [Oct1a/Dcode-Editor#1]
![image](https://user-images.githubusercontent.com/12387480/120782862-04e9e580-c55d-11eb-96ad-b2ef22effc05.png)
yarn 和 npm 都已经试过了

**Comment by Oct1a** [comment]
> ![image](https://user-images.githubusercontent.com/12387480/120782862-04e9e580-c55d-11eb-96ad-b2ef22effc05.png)
> yarn 和 npm 都已经试过了

用cnpm

**Comment by Oct1a** [comment]
过两天我会写个文档教程

**Comment by jiadaoyun** [comment]
> 过两天我会写个文档教程

cnpm也不行，安心等你的文档了呀

**Comment by Oct1a** [comment]
> > 过两天我会写个文档教程
> 
> cnpm也不行，安心等你的文档了呀

用cnpm安装的时候报什么错，截图我看下

**Comment by jiadaoyun** [comment]
> > > 过两天我会写个文档教程
> > 
> > 
> > cnpm也不行，安心等你的文档了呀
> 
> 用cnpm安装的时候报什么错，截图我看下

 我又试了下，可以跑起来了，感谢~~
 另外，求一下在docker里的部署方法呀

**Comment by Oct1a** [comment]
> > > > 过两天我会写个文档教程
> > > 
> > > 
> > > cnpm也不行，安心等你的文档了呀
> > 
> > 
> > 用cnpm安装的时候报什么错，截图我看下
> 
> 我又试了下，可以跑起来了，感谢~~
> 另外，求一下在docker里的部署方法呀
这个没试过，不太清楚
