### ISSUE TITLE
cnpm -i 报错

### ISSUE THREAD

**Issue by chibm** [Oct1a/Dcode-Editor#5]
In file included from /root/.node-gyp/16.18.1/include/node/v8.h:30,
                 from /root/.node-gyp/16.18.1/include/node/node.h:73,
                 from ../../_nan@2.17.0@nan/nan.h:60,
                 from ../src/binding.cpp:1:
/root/.node-gyp/16.18.1/include/node/v8-internal.h: In function ‘void v8::internal::PerformCastCheck(T*)’:
/root/.node-gyp/16.18.1/include/node/v8-internal.h:492:38: error: ‘remove_cv_t’ is not a member of ‘std’
             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                      ^~~~~~~~~~~
/root/.node-gyp/16.18.1/include/node/v8-internal.h:492:38: note: suggested alternative: ‘remove_cv’
             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                      ^~~~~~~~~~~
                                      remove_cv
/root/.node-gyp/16.18.1/include/node/v8-internal.h:492:38: error: ‘remove_cv_t’ is not a member of ‘std’
/root/.node-gyp/16.18.1/include/node/v8-internal.h:492:38: note: suggested alternative: ‘remove_cv’
             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                      ^~~~~~~~~~~
                                      remove_cv
/root/.node-gyp/16.18.1/include/node/v8-internal.h:492:50: error: template argument 2 is invalid
             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                                  ^
/root/.node-gyp/16.18.1/include/node/v8-internal.h:492:63: error: ‘::Perform’ has not been declared
             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                                               ^~~~~~~
/root/.node-gyp/16.18.1/include/node/v8-internal.h:492:63: note: suggested alternative: ‘herror’
             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                                               ^~~~~~~
                                                               herror
../src/binding.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE render(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/binding.cpp:284:98: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     int status = uv_queue_work(uv_default_loop(), &ctx_w->request, compile_it, (uv_after_work_cb)MakeCallback);
                                                                                                  ^~~~~~~~~~~~
../src/binding.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE render_file(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/binding.cpp:320:98: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     int status = uv_queue_work(uv_default_loop(), &ctx_w->request, compile_it, (uv_after_work_cb)MakeCallback);
                                                                                                  ^~~~~~~~~~~~
In file included from ../../_nan@2.17.0@nan/nan.h:60,
                 from ../src/binding.cpp:1:
../src/binding.cpp: At global scope:
/root/.node-gyp/16.18.1/include/node/node.h:887:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/root/.node-gyp/16.18.1/include/node/node.h:921:3: note: in expansion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/binding.cpp:358:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(binding, RegisterModule);
 ^~~~~~~~~~~
make: *** [binding.target.mk:133: Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/dcode/Dcode-Editor/node_modules/_node-sass@4.14.1@node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/dcode/Dcode-Editor/node_modules/_node-gyp@3.8.0@node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Linux 4.19.0-18-amd64
gyp ERR! command "/usr/bin/node" "/home/dcode/Dcode-Editor/node_modules/_node-gyp@3.8.0@node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/dcode/Dcode-Editor/node_modules/_node-sass@4.14.1@node-sass
gyp ERR! node -v v16.18.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
[npminstall:runscript:error] node-sass@^4.9.0 scripts.postinstall run "node scripts/build.js" error: Error [RunScriptError]: Run "sh -c node scripts/build.js" error, exit code 1
    at ChildProcess.<anonymous> (/usr/lib/node_modules/cnpm/node_modules/runscript/index.js:96:21)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12) {
  stdio: [Object],
  exitcode: 1
}
✖ Install fail! RunScriptError: post install error, please remove node_modules before retry!
Run "sh -c node scripts/build.js" error, exit code 1
RunScriptError: Run "sh -c node scripts/build.js" error, exit code 1
    at ChildProcess.<anonymous> (/usr/lib/node_modules/cnpm/node_modules/runscript/index.js:96:21)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
npminstall version: 6.6.1
npminstall args: /usr/bin/node /usr/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --fix-bug-versions --china --userconfig=/root/.cnpmrc --disturl=https://npmmirror.com/mirrors/node --registry=https://registry.npmmirror.com

**Comment by Oct1a** [comment]
> In file included from /root/.node-gyp/16.18.1/include/node/v8.h:30, from /root/.node-gyp/16.18.1/include/node/node.h:73, from ../../_nan@2.17.0@nan/nan.h:60, from ../src/binding.cpp:1: /root/.node-gyp/16.18.1/include/node/v8-internal.h: In function ‘void v8::internal::PerformCastCheck(T*)’: /root/.node-gyp/16.18.1/include/node/v8-internal.h:492:38: error: ‘remove_cv_t’ is not a member of ‘std’ !std::is_same<Data, std::remove_cv_t>::value>::Perform(data); ^~~~~~~~~~~ /root/.node-gyp/16.18.1/include/node/v8-internal.h:492:38: note: suggested alternative: ‘remove_cv’ !std::is_same<Data, std::remove_cv_t>::value>::Perform(data); ^~~~~~~~~~~ remove_cv /root/.node-gyp/16.18.1/include/node/v8-internal.h:492:38: error: ‘remove_cv_t’ is not a member of ‘std’ /root/.node-gyp/16.18.1/include/node/v8-internal.h:492:38: note: suggested alternative: ‘remove_cv’ !std::is_same<Data, std::remove_cv_t>::value>::Perform(data); ^~~~~~~~~~~ remove_cv /root/.node-gyp/16.18.1/include/node/v8-internal.h:492:50: error: template argument 2 is invalid !std::is_same<Data, std::remove_cv_t>::value>::Perform(data); ^ /root/.node-gyp/16.18.1/include/node/v8-internal.h:492:63: error: ‘::Perform’ has not been declared !std::is_same<Data, std::remove_cv_t>::value>::Perform(data); ^~~~~~~ /root/.node-gyp/16.18.1/include/node/v8-internal.h:492:63: note: suggested alternative: ‘herror’ !std::is_same<Data, std::remove_cv_t>::value>::Perform(data); ^~~~~~~ herror ../src/binding.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE render(Nan::NAN_METHOD_ARGS_TYPE)’: ../src/binding.cpp:284:98: warning: cast between incompatible function types from ‘void (_)(uv_work_t_)’ {aka ‘void (_)(uv_work_s_)’} to ‘uv_after_work_cb’ {aka ‘void (_)(uv_work_s_, int)’} [-Wcast-function-type] int status = uv_queue_work(uv_default_loop(), &ctx_w->request, compile_it, (uv_after_work_cb)MakeCallback); ^~~~~~~~~~~~ ../src/binding.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE render_file(Nan::NAN_METHOD_ARGS_TYPE)’: ../src/binding.cpp:320:98: warning: cast between incompatible function types from ‘void (_)(uv_work_t_)’ {aka ‘void (_)(uv_work_s_)’} to ‘uv_after_work_cb’ {aka ‘void (_)(uv_work_s_, int)’} [-Wcast-function-type] int status = uv_queue_work(uv_default_loop(), &ctx_w->request, compile_it, (uv_after_work_cb)MakeCallback); ^~~~~~~~~~~~ In file included from ../../_nan@2.17.0@nan/nan.h:60, from ../src/binding.cpp:1: ../src/binding.cpp: At global scope: /root/.node-gyp/16.18.1/include/node/node.h:887:43: warning: cast between incompatible function types from ‘void (_)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (_)(v8::Localv8::Object)’} to ‘node::addon_register_func’ {aka ‘void (_)(v8::Localv8::Object, v8::Localv8::Value, void_)’} [-Wcast-function-type] (node::addon_register_func) (regfunc), ^ /root/.node-gyp/16.18.1/include/node/node.h:921:3: note: in expansion of macro ‘NODE_MODULE_X’ NODE_MODULE_X(modname, regfunc, NULL, 0) // NOLINT (readability/null_usage) ^~~~~~~~~~~~~ ../src/binding.cpp:358:1: note: in expansion of macro ‘NODE_MODULE’ NODE_MODULE(binding, RegisterModule); ^~~~~~~~~~~ make: *** [binding.target.mk:133: Release/obj.target/binding/src/binding.o] Error 1 make: Leaving directory '/home/dcode/Dcode-Editor/node_modules/_node-sass@4.14.1@node-sass/build' gyp ERR! build error gyp ERR! stack Error: `make` failed with exit code: 2 gyp ERR! stack at ChildProcess.onExit (/home/dcode/Dcode-Editor/node_modules/_node-gyp@3.8.0@node-gyp/lib/build.js:262:23) gyp ERR! stack at ChildProcess.emit (node:events:513:28) gyp ERR! stack at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12) gyp ERR! System Linux 4.19.0-18-amd64 gyp ERR! command "/usr/bin/node" "/home/dcode/Dcode-Editor/node_modules/_node-gyp@3.8.0@node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library=" gyp ERR! cwd /home/dcode/Dcode-Editor/node_modules/_node-sass@4.14.1@node-sass gyp ERR! node -v v16.18.1 gyp ERR! node-gyp -v v3.8.0 gyp ERR! not ok Build failed with error code: 1 [npminstall:runscript:error] node-sass@^4.9.0 scripts.postinstall run "node scripts/build.js" error: Error [RunScriptError]: Run "sh -c node scripts/build.js" error, exit code 1 at ChildProcess. (/usr/lib/node_modules/cnpm/node_modules/runscript/index.js:96:21) at ChildProcess.emit (node:events:513:28) at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12) { stdio: [Object], exitcode: 1 } ✖ Install fail! RunScriptError: post install error, please remove node_modules before retry! Run "sh -c node scripts/build.js" error, exit code 1 RunScriptError: Run "sh -c node scripts/build.js" error, exit code 1 at ChildProcess. (/usr/lib/node_modules/cnpm/node_modules/runscript/index.js:96:21) at ChildProcess.emit (node:events:513:28) at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12) npminstall version: 6.6.1 npminstall args: /usr/bin/node /usr/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --fix-bug-versions --china --userconfig=/root/.cnpmrc --disturl=https://npmmirror.com/mirrors/node --registry=https://registry.npmmirror.com

因为nodejs的版本太高，导致的node-sass不兼容问题，可以根据这篇文章提示修改后重新构建看下https://blog.csdn.net/weixin_38285351/article/details/123503588

**Comment by chibm** [comment]
确实是node版本太高

降级到14.x,可以了
